### ISSUE TITLE
關於ActionMail設定和發送的問題

### ISSUE THREAD

**Issue by sophia1215** [rubytaiwan/AMA#105]
各位大大好：
今天嘗試了 **ihower大大** 聖經上 [_ActionMailer - E-mail 發送_的練習](https://ihower.tw/rails4/actionmailer.html)，有兩大困惑，以下是我照作的設定：
_config/environments/development.rb_

``` ruby
config.action_mailer.raise_delivery_errors = true
config.action_mailer.delivery_method = :letter_opener
config.action_mailer.perform_deliveries = true
config.action_mailer.default_url_options = { host: "http://localhost:3000" }
config.action_mailer.smtp_settings = config_for(:email).symbolize_keys
```

_config/environments/production.rb_

``` ruby
config.action_mailer.raise_delivery_errors = true
config.action_mailer.delivery_method = :smtp
config.action_mailer.perform_deliveries = true
config.action_mailer.default_url_options = { host: 'https://xxxxxx.herokuapp.com/', port: 3000 }
config.action_mailer.smtp_settings = config_for(:email).symbolize_keys
```

根據**ihower大大**聖經上的建議，沒把帳密寫死，我另拆出了一個設定檔：_config/email.yml_

``` ruby
development:
  address: "smtp.gmail.com"
  port: 587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "myemail@gmail.com"
  password: "123456"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "myemail@gmail.com"
  password: "1234567890"
  enable_starttls_auto: true
```

最後也乖乖的把 _config/email.yml_ 加到我的 _. gitignore_ 列表中:

``` ruby
# Ignore bundler config.
/.bundle

# Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
/tmp

# Ignore email.yml
/config/email.yml
```

可是push到heroku時，被 reject：

```
remote:        Could not load configuration. No such file - /tmp/build_53954b8cefeac848ea050f1f5db0ea17/config/email.yml
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:234:in `config_for'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/config/environments/production.rb:84:in `block in <top (required)>'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/railtie.rb:210:in `instance_eval'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/railtie.rb:210:in `configure'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/config/environments/production.rb:1:in `<top (required)>'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:597:in `each'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/engine.rb:597:in `block in <class:Engine>'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `each'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:44:in `tsort_each_child'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_53954b8cefeac848ea050f1f5db0ea17/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote: 
remote:  !     Push rejected, failed to compile Ruby app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to xxxxxx.
remote: 
To https://git.heroku.com/xxxxxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/xxxxxx.git'
```

我Google到一則一樣的[案例](http://stackoverflow.com/questions/26118951/errnoenoent-no-such-file-or-director-config-settings-yml-heroku-deploy)，他的解法就是把我們特意寫入.gitignore列表中的 email.yml 設定檔再push上去：

``` ruby
$ git add config/email.yml
$ git commit -m 'adding email settings'
$ git push heroku master
```

Q1:為什麼呢？那裡面不是有重要的帳密嗎？
Q2:錯誤訊息好像都是在 _/tmp/_ 資料夾下面！我的 _. gitignore_ 列表是不是也該改一下呢？

``` ruby
# Ignore bundler config.
/.bundle

# Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
# tmp 資料夾下面的檔案應該都不需要上傳吧???   <<<-------Here
/tmp/* 

# Ignore email.yml
/config/email.yml
```

**Comment by dlackty** [comment]
可以這樣做：把 `email.yml` 改成：

``` yaml
production:
  address: "smtp.mailgun.org"
  port: 587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["EMAIL_USERNAME"] %>
  password: <%= ENV["EMAIL_PASSWORD"] %>
  enable_starttls_auto: true
```

然後把 `.gitignore` 的 `email.yml` 拿掉並把檔案 commit 進去。

最後透過 `heroku config:set EMAIL_USERNAME=YOUR-USERNAME EMAIL_PASSWORD=YOUR-PASSWORD` 來把密碼透過環境變數設定給 Heroku 的 app。

Rails 4.1 之後有加入 [config/secrets.yml](http://rails.ruby.tw/4_1_release_notes.html#config-secrets-yml) 檔案，做的事情相當類似，可以參考一下，或是直接使用該設定檔儲存你的 Email 帳號密碼。

**Comment by sophia1215** [comment]
@dlackty 感謝大大解答！
可是天黑了，我還是沒試出來 > <
在 Heroku 上光用 Gmail 是不是不能收發信呢？
一定要用 [Add-ons](https://elements.heroku.com/addons#email-sms) 嗎？
