### ISSUE TITLE
capistrino 無法啟動 staging server 上的 sidekiq

### ISSUE THREAD

**Issue by jcsky** [rubytaiwan/AMA#111]
我 deploy 到 staging server 後，發出的email卻還是使用舊的內文
在 staging 的 current/app/views/personal_mailer/waitting_for_start.html.erb 確認內文確實已改成新的了
但發出的mail 還是...舊的!!
也試過了 touch restart.txt 重開 passenger server，無效..

使用的是 sidekiq + redis 非同步發mail

**environment/staging.rb**

``` ruby
Rails.application.configure do
  config.cache_classes = true
  config.eager_load = true
  config.consider_all_requests_local       = false
  config.action_controller.perform_caching = true
  config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?
  config.assets.js_compressor = :uglifier
  config.assets.compile = false
  config.assets.digest = true
  config.log_level = :debug
  config.cache_store = :redis_store, 'redis://localhost:6379/0', {
    expires_in: 90.minutes,
    namespace: 'lucky8_cache'
  }

  config.action_mailer.default_url_options               = {
    host: Settings.domain
  }

  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address:              'smtp.mandrillapp.com',
    port:                 587,
    user_name:            Settings.mandrill_user_name,
    password:             Settings.mandrill_api_key,
    authentication:       'plain',
    enable_starttls_auto: true
  }

  config.i18n.fallbacks = true

  config.active_support.deprecation = :notify

  config.log_formatter = ::Logger::Formatter.new

  config.active_record.dump_schema_after_migration = false
end
```

**deploy.rb**

``` ruby
`ssh-add`

set :application, "lottery"

set :scm, :git
set :repo_url, "git@github.com:wish8/lottery.git"
set :deploy_to, "/home/apps/lottery"

set :keep_releases, 5
set :passenger_restart_with_touch, true

set :linked_files, %w{config/database.yml config/application.yml config/secrets.yml}
set :linked_dirs, %w{uploads config/certs log}

set :passenger_restart_with_touch, true

namespace :deploy do

  after :restart, :clear_cache do
    on roles(:web), in: :groups, limit: 3, wait: 10 do

    end
  end

end
```

**capfile**

``` ruby
# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/faster_assets'
require 'capistrano/rails/migrations'
require 'capistrano/passenger'
require 'capistrano/sidekiq'
```

**Comment by jcsky** [comment]
執行了 cap staging sidekiq:restart 還是沒有改變 ..

```
Identity added: /Users/sky/.ssh/id_rsa (/Users/sky/.ssh/id_rsa)
DEBUG [1f043c36] Running ~/.rvm/bin/rvm version as apps@tw-staging.lucky8.tw
DEBUG [1f043c36] Command: ~/.rvm/bin/rvm version
DEBUG [1f043c36]    rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [1f043c36] Finished in 1.467 seconds with exit status 0 (successful).
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [68e53e9f] Running ~/.rvm/bin/rvm current as apps@tw-staging.lucky8.tw
DEBUG [68e53e9f] Command: ~/.rvm/bin/rvm current
DEBUG [68e53e9f]    ruby-2.3.0
DEBUG [68e53e9f] Finished in 0.232 seconds with exit status 0 (successful).
ruby-2.3.0
DEBUG [5ce68791] Running ~/.rvm/bin/rvm 2.3.0 do ruby --version as apps@tw-staging.lucky8.tw
DEBUG [5ce68791] Command: ~/.rvm/bin/rvm 2.3.0 do ruby --version
DEBUG [5ce68791]    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
DEBUG [5ce68791] Finished in 0.322 seconds with exit status 0 (successful).
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
DEBUG [fb5502ef] Running /usr/bin/env [ -d /home/apps/lottery/current ] as apps@tw-staging.lucky8.tw
DEBUG [fb5502ef] Command: [ -d /home/apps/lottery/current ]
DEBUG [fb5502ef] Finished in 0.101 seconds with exit status 0 (successful).
DEBUG [36e4d7db] Running /usr/bin/env if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi as apps@tw-staging.lucky8.tw
DEBUG [36e4d7db] Command: if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi
DEBUG [36e4d7db] Finished in 0.105 seconds with exit status 0 (successful).
DEBUG [fd8ac566] Running /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid ] as apps@tw-staging.lucky8.tw
DEBUG [fd8ac566] Command: cd /home/apps/lottery/current && /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid ]
DEBUG [fd8ac566] Finished in 0.105 seconds with exit status 1 (failed).
DEBUG [4c3e3ee6] Running /usr/bin/env if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi as apps@tw-staging.lucky8.tw
DEBUG [4c3e3ee6] Command: if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi
DEBUG [4c3e3ee6] Finished in 0.104 seconds with exit status 0 (successful).
DEBUG [8243e290] Running /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid ] as apps@tw-staging.lucky8.tw
DEBUG [8243e290] Command: cd /home/apps/lottery/current && /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid ]
DEBUG [8243e290] Finished in 0.105 seconds with exit status 1 (failed).
INFO [f762bb27] Running ~/.rvm/bin/rvm 2.3.0 do bundle exec sidekiq --index 0 --pidfile /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid --environment staging --logfile /home/apps/lottery/shared/log/sidekiq.log --daemon as apps@tw-staging.lucky8.tw
DEBUG [f762bb27] Command: cd /home/apps/lottery/current && ~/.rvm/bin/rvm 2.3.0 do bundle exec sidekiq --index 0 --pidfile /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid --environment staging --logfile /home/apps/lottery/shared/log/sidekiq.log --daemon
INFO [f762bb27] Finished in 0.871 seconds with exit status 0 (successful).
```

**Comment by hrs113355** [comment]
你可能需要利用 `top` 或 `ps aux | grep sidekiq` 確認 sidekiq 是否有正確 restart

**Comment by jcsky** [comment]
回報一下，奮戰了半天後...(暈)
終於剛剛依 @hrs113355 提的監看了一下 sidekiq pid 沒變
在kill -9 pid (強制結束 sidekiq process)後重啟，解決了這個問題，謝謝大家~!

不過cap staging sidekiq:restart 為什麼沒能重啟就還不知道 @@

**Comment by hrs113355** [comment]
看你的 log 中，`sidekiq stop` 的那一個步驟因為沒有找到紀錄 pid 檔而沒有正常關閉先前的 sidekiq process，你可能需要確認是因為先前沒有正常啟動 / 關閉，還是因為 pid 檔的檔名或存放路徑有誤。

**Comment by jcsky** [comment]
喔喔~!!
我的 sidekiq 是用這指命啟動的 
`bundle exec sidekiq -d -L log/sidekiq.log -C config/sidekiq.yml -e production`
我來確認一下pid檔路徑等等

**Comment by jcsky** [comment]
[28caaecd] Command: cd /home/apps/lottery/current && /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid ]
DEBUG [28caaecd] Finished in 0.114 seconds with exit status 1 (failed).

我試著去執行它的指令 /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid ]
但沒有任何訊息和錯誤，sidekiq的process也沒有因此跑起來

sidekiq.log

```
No such file or directory @ rb_sysopen - /home/apps/lottery/shared/tmp/pids/sidekiq-0.pid
/home/apps/lottery/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:365:in `initialize'
/home/apps/lottery/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:365:in `open'
/home/apps/lottery/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:365:in `write_pid'
/home/apps/lottery/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.3/lib/sidekiq/cli.rb:42:in `parse'
/home/apps/lottery/shared/bundle/ruby/2.3.0/gems/sidekiq-3.5.3/bin/sidekiq:12:in `<top (required)>'
/home/apps/lottery/shared/bundle/ruby/2.3.0/bin/sidekiq:23:in `load'
/home/apps/lottery/shared/bundle/ruby/2.3.0/bin/sidekiq:23:in `<main>'
```

No such file .. 執行的時候要怎麼讓pid檔產生在這個路徑呢 @@

**Comment by jcsky** [comment]
我試著去  touch shared/tmp/pids/sidekiq-0.pid
但結果會出現 invalid pid
我移除掉 sidekiq.yml 的 pidfile: /tmp/pids/sidekiq.pid 後
可以跑 bundle exec sidekiq正常運作
不過pid不在/tmp/pids/下，所以 cap staging deploy 及cap相關指令對sidekiq還是沒有作用就是了.. 

不曉得要如何執行  sidekiq 同時讓它的 pid 檔出現在想要的路徑中

server上的 **sidekiq.yml**

```
---
:concurrency: 5


:queues:
    - default

staging:
  :concurrency: 10
production:
  :concurrency: 20
```

**Comment by hrs113355** [comment]
你可以貼一下當你把 development 環境的 `sidekiq.yml` 也把關於 pidfile 的設定拿掉之後，cap `sidekiq:start` 的 log 嗎？

另外 staging 上的 `shared/pids/` 裡有沒有 `sidekiq.pid` ?

**Comment by jcsky** [comment]
staging server 上的 shared/tmp/pids/sidekiq.pid 不存在

```
Identity added: /Users/sky/.ssh/id_rsa (/Users/sky/.ssh/id_rsa)
DEBUG [7bb1be10] Running ~/.rvm/bin/rvm version as apps@tw-staging.lucky8.tw
DEBUG [7bb1be10] Command: ~/.rvm/bin/rvm version
DEBUG [7bb1be10]    rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [7bb1be10] Finished in 1.100 seconds with exit status 0 (successful).
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [1b2d620d] Running ~/.rvm/bin/rvm current as apps@tw-staging.lucky8.tw
DEBUG [1b2d620d] Command: ~/.rvm/bin/rvm current
DEBUG [1b2d620d]    ruby-2.3.0
DEBUG [1b2d620d] Finished in 0.242 seconds with exit status 0 (successful).
ruby-2.3.0
DEBUG [646a1184] Running ~/.rvm/bin/rvm 2.3.0 do ruby --version as apps@tw-staging.lucky8.tw
DEBUG [646a1184] Command: ~/.rvm/bin/rvm 2.3.0 do ruby --version
DEBUG [646a1184]    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
DEBUG [646a1184] Finished in 0.329 seconds with exit status 0 (successful).
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
DEBUG [22804227] Running /usr/bin/env if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi as apps@tw-staging.lucky8.tw
DEBUG [22804227] Command: if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi
DEBUG [22804227] Finished in 0.115 seconds with exit status 0 (successful).
DEBUG [a36514aa] Running /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq.pid ] as apps@tw-staging.lucky8.tw
DEBUG [a36514aa] Command: cd /home/apps/lottery/current && /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq.pid ]
DEBUG [a36514aa] Finished in 0.116 seconds with exit status 0 (successful).
DEBUG [d440f115] Running /usr/bin/env kill -0 $( cat /home/apps/lottery/shared/tmp/pids/sidekiq.pid ) as apps@tw-staging.lucky8.tw
DEBUG [d440f115] Command: cd /home/apps/lottery/current && /usr/bin/env kill -0 $( cat /home/apps/lottery/shared/tmp/pids/sidekiq.pid )
DEBUG [d440f115] Finished in 0.110 seconds with exit status 1 (failed).
INFO [dccc7458] Running ~/.rvm/bin/rvm 2.3.0 do bundle exec sidekiq --index 0 --pidfile /home/apps/lottery/shared/tmp/pids/sidekiq.pid --environment staging --logfile /home/apps/lottery/shared/log/sidekiq.log --daemon as apps@tw-staging.lucky8.tw
DEBUG [dccc7458] Command: cd /home/apps/lottery/current && ~/.rvm/bin/rvm 2.3.0 do bundle exec sidekiq --index 0 --pidfile /home/apps/lottery/shared/tmp/pids/sidekiq.pid --environment staging --logfile /home/apps/lottery/shared/log/sidekiq.log --daemon
INFO [dccc7458] Finished in 0.960 seconds with exit status 0 (successful).
```

**Comment by hrs113355** [comment]
跑完這一次之後應該 pidfile 會出現了XD?

**Comment by jcsky** [comment]
真的有耶~!!! O_O

不過同樣我在 cap production sidekiq:start 怎麼還是沒有 pidfile @@

```
DEBUG [70dc8942] Running /usr/bin/env [ -d ~/.rvm ] as apps@lucky8.tw
DEBUG [70dc8942] Command: [ -d ~/.rvm ]
DEBUG [70dc8942] Finished in 1.358 seconds with exit status 0 (successful).
DEBUG [c56a86fb] Running ~/.rvm/bin/rvm version as apps@lucky8.tw
DEBUG [c56a86fb] Command: ~/.rvm/bin/rvm version
DEBUG [c56a86fb]    rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [c56a86fb] Finished in 0.253 seconds with exit status 0 (successful).
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
DEBUG [7d384abc] Running ~/.rvm/bin/rvm current as apps@lucky8.tw
DEBUG [7d384abc] Command: ~/.rvm/bin/rvm current
DEBUG [7d384abc]    ruby-2.3.0
DEBUG [7d384abc] Finished in 0.256 seconds with exit status 0 (successful).
ruby-2.3.0
DEBUG [b1abc8c2] Running ~/.rvm/bin/rvm default do ruby --version as apps@lucky8.tw
DEBUG [b1abc8c2] Command: ~/.rvm/bin/rvm default do ruby --version
DEBUG [b1abc8c2]    ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
DEBUG [b1abc8c2] Finished in 0.629 seconds with exit status 0 (successful).
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
DEBUG [4ca791bc] Running /usr/bin/env if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi as apps@lucky8.tw
DEBUG [4ca791bc] Command: if test ! -d /home/apps/lottery/current; then echo "Directory does not exist '/home/apps/lottery/current'" 1>&2; false; fi
DEBUG [4ca791bc] Finished in 0.105 seconds with exit status 0 (successful).
DEBUG [e8c193cf] Running /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq.pid ] as apps@lucky8.tw
DEBUG [e8c193cf] Command: cd /home/apps/lottery/current && /usr/bin/env [ -f /home/apps/lottery/shared/tmp/pids/sidekiq.pid ]
DEBUG [e8c193cf] Finished in 0.106 seconds with exit status 1 (failed).
INFO [14481fd7] Running ~/.rvm/bin/rvm default do bundle exec sidekiq --index 0 --pidfile /home/apps/lottery/shared/tmp/pids/sidekiq.pid --environment production --logfile /home/apps/lottery/shared/log/sidekiq.log --daemon as apps@lucky8.tw
DEBUG [14481fd7] Command: cd /home/apps/lottery/current && ~/.rvm/bin/rvm default do bundle exec sidekiq --index 0 --pidfile /home/apps/lottery/shared/tmp/pids/sidekiq.pid --environment production --logfile /home/apps/lottery/shared/log/sidekiq.log --daemon
INFO [14481fd7] Finished in 1.018 seconds with exit status 0 (successful).
```

**Comment by jcsky** [comment]
OK~!! 我知道了.....
在 production 下，我建好 lottery/shared/tmp/pids 資料夾後
再打 `cap production sidekiq:start`
pidfile 就出來了!!

所以.. 這個 issue 的結論應該是，要先建好`shared/tmp/pids`資料夾，就這樣!! 
感動... Q_Q

**Comment by jcsky** [comment]
感謝 @hrs113355 大大火力支援
