### ISSUE TITLE
部署到 digitalocean 後， devise 問題

### ISSUE THREAD

**Issue by eric0324** [rubytaiwan/AMA#124]
請教大家一個問題，

我參考這篇：
https://www.digitalocean.com/community/tutorials/how-to-use-the-ruby-on-rails-one-click-application-on-digitalocean

部署在digitalocean 後，在以下動作
- 按下註冊後
- 登出
- 登入
  都會出現附圖的問題

![Imgur](http://i.imgur.com/jCKfX63.png)

logs 的部分

```
 [2016-05-05T02:26:43.388101 #2529]  INFO -- : Started GET "/user" for 162.158.176.185 at 2016-05-05 02:26:43 -0400
F, [2016-05-05T02:26:43.391041 #2529] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/user"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  unicorn (5.1.0) lib/unicorn/http_server.rb:562:in `process_client'
```

我的 `route.rb` 設定

``` Ruby
Rails.application.routes.draw do
  get 'static_pages/about'
  get 'activity/index'
  get 'donecase/index'

  resources :boards
  devise_for :users
  resources :users
   resources :ideas do
    resources :needs
   end

 root :to => 'ideas#index'
end
```

麻煩各位指導一下小弟，感謝。

**Comment by imgarylai** [comment]
你的登入、註冊、登出的helper可以貼出來看一下嗎？

**Comment by eric0324** [comment]
下面分別是登入登出

``` ruby
<%= link_to t("common.login"), new_user_session_path, class: "btn btn-default" %>
<%= link_to t("common.logout"), destroy_user_session_path, method: :delete %>
```

再來是我要在首頁 `ideas`放一個註冊的表單 ，所我另外在 `index.html.erb` 製作一個註冊表格

``` ruby
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
 <div class="form-inputs">
   <%= f.input :email,:label => t("common.email"), required: true, autofocus: true %>
   <%= f.input :name,:label => t("common.name"), required: true %>
   <%= f.input :password,:label => t("comon.password"), required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
   <%= f.input :password_confirmation,:label => t("common.passwordConfirmation"), required: true %>
</div>
<div class="form-actions">
   <%= f.button :submit, t("common.signedUp") %>
</div>
<%end %>

```

Devise 原本給的註冊頁面也有相同問題

**Comment by kuroro0718** [comment]
你routes那邊是不是有typo?
resources :Ideas do 應該改成:ideas
在local端的錯誤訊息是什麼呢？

**Comment by eric0324** [comment]
@kuroro0718 那個地方我已經改成 :ideas 了，還是有這個問題呢 😢

**Comment by kuroro0718** [comment]
在terminal下輸入rake routes，把結果貼出來
會不會是你deploy後沒正確安裝gem呢？
那篇文章有提到需要在terminal下輸入bundle install，然後重開unicorn

**Comment by eric0324** [comment]
輸入 `rake routes` 後，`user` 的 `routes`：

![Imgur](http://i.imgur.com/w9jAF9c.png)

我已經下過 `bundle install` 看似都有正確安裝進去

不過在 `bundle install` 過程中，出現一行：

![Imgur](http://i.imgur.com/J8FIRwO.png)

感覺應該不是這問題。

**Comment by seansg** [comment]
bundler 的問題你可能要確認一下你在遠端用的ruby環境是user的還是system

**Comment by eric0324** [comment]
@bih00425  不好意思，小弟不才，請問一下要怎麼確認自己是用user的還是system環境？

我是這樣使用的：

```
# rvm all do ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by seansg** [comment]
你可以下which ruby看ruby是裝在哪裡
如果不是在/home/xxx/下的話，就需要有sudo的權限或另外設定
不過這應該離題了
另外我看到你貼的rake routes中都是/users
看你的錯誤訊息裡面是/user
所以你再確認一下吧

**Comment by eric0324** [comment]
路徑是：
/usr/local/rvm/rubies/ruby-2.2.1/bin/ruby

恩對，因為我只有貼出 user 的部分 :P

**Comment by ihower** [comment]
devise 的登入的網址應該是 /users/sign_in，但是你的錯誤 log 中你點的網址是 /user

**Comment by eric0324** [comment]
@ihower 所以是我 routes 的問題囉？

**Comment by ihower** [comment]
你確定你點的是 `<%= link_to t("common.login"), new_user_session_path, class: "btn btn-default" %>` 這個超連結? 這就是 `/users/sign_in`。

**Comment by eric0324** [comment]
這個可以 work ，目前剩下登出、註冊

登出會跑到 `/users/sign_out` ，而且重新整理幾次居然就會成功登出
註冊會跑到 `/users`

感謝各位大大耐心教小弟

**Comment by eric0324** [comment]
我嘗試把

```
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
```

換成

```
<%= javascript_include_tag "defaults", "data-turbolinks-track" => true %>
```

居然就可以登出了。

現在只剩下註冊的部分輸入完資料，按下註冊後，還是會錯誤

**Comment by eric0324** [comment]
我用了 Swap 之後，再重新 `bundle install` 之後就成功了！

感謝各位幫助！
